import HeaderBar from "../../components/HeaderBar";
import BeginnerPanel from "../../components/BeginnerPanel";
import TopSignals from "../../components/TopSignals";
import AlertFeed from "../../components/AlertFeed";
import Glossary from "../../components/Glossary";
import BeginnerSettings from "../../components/BeginnerSettings";
import BeginnerTicket from "../../components/BeginnerTicket";
import DailyPL from "../../components/DailyPL";
import PaperHistory from "../../components/PaperHistory";
